<?php

namespace AppBundle\Repository;

/**
 * SkewerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkewerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll() 
  { 
    return $this->getEntityManager() 
      ->createQuery( 
        "SELECT skewer FROM AppBundle:Skewer skewer" 
                                    
      ) 
      ->getResult(); 
  } 
 

}
