<?php

namespace AppBundle\Repository;

/**
 * TmpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TmpRepository extends \Doctrine\ORM\EntityRepository
{
}
